server:
  port: 9527


spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh # 路由的ID，没有固定规则，但是要求唯一
#          uri: http://localhost:8001 # 路由地址
          uri: lb://cloud-payment-service # 这里写的是Eureka里的地址
          predicates:
            - Path=/payment/getPaymentById/** # 匹配路径 # 以上组合起来就是访问 http://localhost:8001/payment/getPaymentById/**
#            - After=2023-04-10T03:41:01.731+08:00[Asia/Shanghai] # 在这个时间之后访问才会成功
#            - Cookie=username,abc # 必须带上这个cookie才能访问
#            - Header=x-Request-Id, \d+ # 请求头要有 x-Request-Id属性，并且值为整数【后面那个是正则】
#            - Method=GET
#            - Query=username,abc

        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/gatewayTest
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由功能，利用微服务名称进行路由

eureka:
  client:
    register-with-eureka: true # 表示注册进Eureka
    fetch-registry: true #是否从Eureka抓取已有信息，默认为true，集群必须true，才能配合Ribbon使用负载均衡
    service-url:
      # defaultZone: http://localhost:7001/eureka # 写Eureka的地址 【单机版】
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka

