server:
  port: 8001

spring:
  application:
    name: cloud-provider-hystrix-payment

eureka:
  client:
    register-with-eureka: true # 表示注册进Eureka
    fetch-registry: true #是否从Eureka抓取已有信息，默认为true，集群必须true，才能配合Ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
